// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmHSxPXprr-wcnm-lYSB36vyuRQmLNKDo',
    appId: '1:40347477880:web:ce0910c8f6e6a134bb4a8d',
    messagingSenderId: '40347477880',
    projectId: 'sitesmart-d2c53',
    authDomain: 'sitesmart-d2c53.firebaseapp.com',
    storageBucket: 'sitesmart-d2c53.firebasestorage.app',
    measurementId: 'G-MTRYD0DCKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLSfhZBmxqbQz62Ix1_q3RT_cDSW_a0o',
    appId: '1:40347477880:android:4a2e59173a0cf233bb4a8d',
    messagingSenderId: '40347477880',
    projectId: 'sitesmart-d2c53',
    storageBucket: 'sitesmart-d2c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbghLlmxgqkeyq5F4MCEozFYTCFSjznXo',
    appId: '1:40347477880:ios:91cb30d38533581fbb4a8d',
    messagingSenderId: '40347477880',
    projectId: 'sitesmart-d2c53',
    storageBucket: 'sitesmart-d2c53.firebasestorage.app',
    iosBundleId: 'com.example.sitesmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbghLlmxgqkeyq5F4MCEozFYTCFSjznXo',
    appId: '1:40347477880:ios:91cb30d38533581fbb4a8d',
    messagingSenderId: '40347477880',
    projectId: 'sitesmart-d2c53',
    storageBucket: 'sitesmart-d2c53.firebasestorage.app',
    iosBundleId: 'com.example.sitesmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmHSxPXprr-wcnm-lYSB36vyuRQmLNKDo',
    appId: '1:40347477880:web:90c7760ab298bcf8bb4a8d',
    messagingSenderId: '40347477880',
    projectId: 'sitesmart-d2c53',
    authDomain: 'sitesmart-d2c53.firebaseapp.com',
    storageBucket: 'sitesmart-d2c53.firebasestorage.app',
    measurementId: 'G-L31CEHWS7R',
  );

}